global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "stock-data-service"
    static_configs:
      - targets: ["stock-data-service:8080"]

  - job_name: "alert-processing-service"
    static_configs:
      - targets: ["alert-processing-service:8081"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8082"]
