# Use an official Node.js runtime as a parent image
FROM node:18.18.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Compile the TypeScript code
RUN npm run gen:proto

# Expose the gRPC server port
EXPOSE 50052

# Define the command to run the application
CMD ["npm", "start"]
